# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(30, 480, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(550, 470, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 47, 13))
        self.label_2.setObjectName("label_2")
        self.key = QtWidgets.QTextEdit(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(120, 260, 451, 41))
        self.key.setObjectName("key")
        self.VIGENERE = QtWidgets.QLabel(self.centralwidget)
        self.VIGENERE.setGeometry(QtCore.QRect(240, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VIGENERE.setFont(font)
        self.VIGENERE.setObjectName("VIGENERE")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 330, 51, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 260, 21, 16))
        self.label_3.setObjectName("label_3")
        self.CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(120, 330, 451, 111))
        self.CipherText.setObjectName("CipherText")
        self.PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(120, 160, 451, 71))
        self.PlainText.setObjectName("PlainText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 151, 71))
        self.label.setObjectName("label")
        self.matrix = QtWidgets.QTextEdit(self.centralwidget)
        self.matrix.setGeometry(QtCore.QRect(120, 90, 451, 41))
        self.matrix.setObjectName("matrix")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.label_5.setObjectName("label_5")
        self.btn_creatematrix = QtWidgets.QPushButton(self.centralwidget)
        self.btn_creatematrix.setGeometry(QtCore.QRect(270, 470, 91, 31))
        self.btn_creatematrix.setObjectName("btn_creatematrix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label_2.setText(_translate("MainWindow", "PlainText"))
        self.VIGENERE.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.label_4.setText(_translate("MainWindow", "CipherText"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.label.setText(_translate("MainWindow", "NGO TAN TAI -2280602794"))
        self.label_5.setText(_translate("MainWindow", "Create matrix"))
        self.btn_creatematrix.setText(_translate("MainWindow", "Create matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
